Python 3.13.7 (tags/v3.13.7:bcee1c3, Aug 14 2025, 14:15:11) [MSC v.1944 64 bit (AMD64)] on win32
Enter "help" below or click "Help" above for more information.
>>> # \n - new/next line
... #\t - tab
... #\\ - backslash
... #\' - insert a single quote inside a single quoted string
... 
... #\n
... print("hello everyone.\nhow are you?")
... 
... 
... #\t
... print("john 20")
... print("jhon\t20")
... 
... #\\
... 
... print("new\\old")
... print("yes\\no")
... 
... # \'
... 
... print("this is python's class")
... print('this is python\'s class')
... 
... 
